begin;

create type public.user_role as enum ('customer', 'super_admin', 'order_manager', 'shipping_manager');
create type public.order_status as enum ('payment_pending', 'paid', 'preparing', 'ready_to_ship', 'shipping', 'delivered', 'cancelled', 'return_requested', 'returned');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  phone text,
  role public.user_role not null default 'customer',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('necklace', 'ring', 'earring')),
  price integer not null check (price >= 0),
  inventory integer not null default 0 check (inventory >= 0),
  material text,
  description text,
  badge text check (badge in ('NEW', 'BEST') or badge is null),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique default ('YJ-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text), 1, 6))),
  user_id uuid not null references public.profiles(id),
  status public.order_status not null default 'payment_pending',
  payment_method text not null default 'bank_transfer',
  subtotal integer not null check (subtotal >= 0),
  shipping_fee integer not null default 3000 check (shipping_fee >= 0),
  total integer not null check (total >= 0),
  recipient_name text not null,
  recipient_phone text not null,
  postal_code text not null,
  address_line1 text not null,
  address_line2 text,
  delivery_memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id integer not null,
  product_name text not null,
  option_name text,
  quantity integer not null check (quantity > 0),
  unit_price integer not null check (unit_price >= 0)
);

create table public.shipments (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  carrier text not null default 'CJ대한통운',
  tracking_number text,
  shipped_at timestamptz,
  delivered_at timestamptz,
  updated_at timestamptz not null default now()
);

create table public.app_settings (
  id integer primary key default 1 check (id = 1),
  carrier text not null default 'CJ대한통운',
  base_shipping_fee integer not null default 3000,
  free_shipping_threshold integer not null default 50000,
  remote_area_fee integer not null default 3000,
  order_alert_email text not null default 'kz4network@gmail.com',
  updated_at timestamptz not null default now()
);

insert into public.app_settings (id) values (1);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and active = true
      and role in ('super_admin', 'order_manager', 'shipping_manager')
  );
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and active = true and role = 'super_admin'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    case when lower(new.email) = 'kz4network@gmail.com' then 'super_admin'::public.user_role else 'customer'::public.user_role end
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.protect_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (new.role is distinct from old.role or new.active is distinct from old.active or new.email is distinct from old.email)
     and not public.is_super_admin() then
    raise exception 'Only a super admin can change account privileges';
  end if;
  return new;
end;
$$;

create trigger protect_profile_privileges
  before update on public.profiles
  for each row execute procedure public.protect_profile_privileges();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.shipments enable row level security;
alter table public.app_settings enable row level security;

create policy "Users read own profile" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "Users update own profile" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "Super admin manages profiles" on public.profiles for update using (public.is_super_admin()) with check (public.is_super_admin());

create policy "Public reads active products" on public.products for select using (active = true or public.is_admin());
create policy "Admins manage products" on public.products for all using (public.is_admin()) with check (public.is_admin());

create policy "Users create own orders" on public.orders for insert with check (user_id = auth.uid());
create policy "Users read own orders" on public.orders for select using (user_id = auth.uid() or public.is_admin());
create policy "Admins update orders" on public.orders for update using (public.is_admin()) with check (public.is_admin());

create policy "Users create own order items" on public.order_items for insert with check (
  exists (select 1 from public.orders where orders.id = order_id and orders.user_id = auth.uid())
);
create policy "Users read own order items" on public.order_items for select using (
  exists (select 1 from public.orders where orders.id = order_id and (orders.user_id = auth.uid() or public.is_admin()))
);

create policy "Users read own shipment" on public.shipments for select using (
  exists (select 1 from public.orders where orders.id = order_id and (orders.user_id = auth.uid() or public.is_admin()))
);
create policy "Admins create shipments" on public.shipments for insert with check (public.is_admin());
create policy "Admins update shipments" on public.shipments for update using (public.is_admin()) with check (public.is_admin());

create policy "Admins read settings" on public.app_settings for select using (public.is_admin());
create policy "Super admin updates settings" on public.app_settings for update using (public.is_super_admin()) with check (public.is_super_admin());

create index orders_user_id_idx on public.orders(user_id);
create index products_active_sort_idx on public.products (active, sort_order, created_at desc);

insert into public.products (id, name, category, price, inventory, material, description, badge, sort_order, active) values
  (1, 'Noir Rose Earrings', 'earring', 49000, 20, '925 Silver', '입체적인 장미 모티프를 절제된 실버 톤으로 완성한 이어링입니다.', 'NEW', 1, true),
  (2, 'Emerald Signet Ring', 'ring', 78000, 20, '925 Silver · Emerald', '선명한 그린 스톤과 단단한 실버 밴드가 균형을 이루는 시그넷 링입니다.', 'BEST', 2, true),
  (3, 'Coin Chain Necklace', 'necklace', 94000, 20, '925 Silver', '빈티지 코인과 서로 다른 체인의 리듬이 매력적인 레이어드 네크리스입니다.', null, 3, true),
  (4, 'Amethyst Bead Necklace', 'necklace', 69000, 20, 'Amethyst · Silver', '차분한 보랏빛 자수정 비즈에 가는 실버 체인을 더한 섬세한 네크리스입니다.', 'NEW', 4, true),
  (5, 'Bold Link Necklace', 'necklace', 109000, 20, '925 Silver', '볼드한 링크가 목선을 따라 자연스럽게 흐르는 존재감 있는 체인 네크리스입니다.', 'BEST', 5, true),
  (6, 'Lapis Coin Necklace', 'necklace', 72000, 20, 'Lapis · Silver', '깊은 청색 비즈와 작은 코인 펜던트가 매일의 룩에 잔잔한 포인트를 줍니다.', null, 6, true),
  (7, 'Classic Curb Necklace', 'necklace', 98000, 20, '925 Silver', '촘촘하게 맞물린 커브 체인의 광택이 단정하고 모던한 인상을 만듭니다.', null, 7, true),
  (8, 'Silver Sphere Necklace', 'necklace', 119000, 20, '925 Silver', '크기가 다른 실버 볼이 리드미컬하게 이어지는 조형적인 네크리스입니다.', 'BEST', 8, true),
  (9, 'Fine Layered Chain', 'necklace', 64000, 20, '925 Silver', '빛을 가볍게 머금는 두 줄의 체인으로 단정하게 레이어링한 네크리스입니다.', null, 9, true),
  (10, 'Garnet Drop Necklace', 'necklace', 76000, 20, 'Garnet · Silver', '와인빛 가넷과 작은 드롭 장식이 차분한 우아함을 전합니다.', 'NEW', 10, true),
  (11, 'Turquoise Collar', 'necklace', 88000, 20, 'Turquoise · Silver', '맑은 터키석 비즈를 촘촘히 엮어 얼굴빛을 생기 있게 밝혀주는 네크리스입니다.', null, 11, true),
  (12, 'Honey Amethyst Necklace', 'necklace', 82000, 20, 'Amethyst · Quartz', '자수정 사이에 따뜻한 꿀빛 스톤을 더한 부드럽고 독특한 조합입니다.', null, 12, true),
  (13, 'Tiger Eye Tail Necklace', 'necklace', 79000, 20, 'Tiger Eye · Silver', '깊은 갈색 타이거아이와 고래 꼬리 펜던트가 자연의 이미지를 담아냅니다.', 'NEW', 13, true)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.products', 'id'), greatest((select max(id) from public.products), 1));
create index orders_status_idx on public.orders(status);
create index orders_created_at_idx on public.orders(created_at desc);
create index order_items_order_id_idx on public.order_items(order_id);

commit;

