begin;

create type public.user_role as enum ('customer', 'super_admin', 'order_manager', 'shipping_manager');
create type public.order_status as enum ('payment_pending', 'paid', 'preparing', 'ready_to_ship', 'shipping', 'delivered', 'cancelled', 'return_requested', 'returned');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  phone text,
  role public.user_role not null default 'customer',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique default ('YJ-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text), 1, 6))),
  user_id uuid not null references public.profiles(id),
  status public.order_status not null default 'payment_pending',
  payment_method text not null default 'bank_transfer',
  subtotal integer not null check (subtotal >= 0),
  shipping_fee integer not null default 3000 check (shipping_fee >= 0),
  total integer not null check (total >= 0),
  recipient_name text not null,
  recipient_phone text not null,
  postal_code text not null,
  address_line1 text not null,
  address_line2 text,
  delivery_memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id integer not null,
  product_name text not null,
  option_name text,
  quantity integer not null check (quantity > 0),
  unit_price integer not null check (unit_price >= 0)
);

create table public.shipments (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  carrier text not null default 'CJ대한통운',
  tracking_number text,
  shipped_at timestamptz,
  delivered_at timestamptz,
  updated_at timestamptz not null default now()
);

create table public.app_settings (
  id integer primary key default 1 check (id = 1),
  carrier text not null default 'CJ대한통운',
  base_shipping_fee integer not null default 3000,
  free_shipping_threshold integer not null default 50000,
  remote_area_fee integer not null default 3000,
  order_alert_email text not null default 'kz4network@gmail.com',
  updated_at timestamptz not null default now()
);

insert into public.app_settings (id) values (1);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and active = true
      and role in ('super_admin', 'order_manager', 'shipping_manager')
  );
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and active = true and role = 'super_admin'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    case when lower(new.email) = 'kz4network@gmail.com' then 'super_admin'::public.user_role else 'customer'::public.user_role end
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.protect_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (new.role is distinct from old.role or new.active is distinct from old.active or new.email is distinct from old.email)
     and not public.is_super_admin() then
    raise exception 'Only a super admin can change account privileges';
  end if;
  return new;
end;
$$;

create trigger protect_profile_privileges
  before update on public.profiles
  for each row execute procedure public.protect_profile_privileges();

alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.shipments enable row level security;
alter table public.app_settings enable row level security;

create policy "Users read own profile" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "Users update own profile" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "Super admin manages profiles" on public.profiles for update using (public.is_super_admin()) with check (public.is_super_admin());

create policy "Users create own orders" on public.orders for insert with check (user_id = auth.uid());
create policy "Users read own orders" on public.orders for select using (user_id = auth.uid() or public.is_admin());
create policy "Admins update orders" on public.orders for update using (public.is_admin()) with check (public.is_admin());

create policy "Users create own order items" on public.order_items for insert with check (
  exists (select 1 from public.orders where orders.id = order_id and orders.user_id = auth.uid())
);
create policy "Users read own order items" on public.order_items for select using (
  exists (select 1 from public.orders where orders.id = order_id and (orders.user_id = auth.uid() or public.is_admin()))
);

create policy "Users read own shipment" on public.shipments for select using (
  exists (select 1 from public.orders where orders.id = order_id and (orders.user_id = auth.uid() or public.is_admin()))
);
create policy "Admins create shipments" on public.shipments for insert with check (public.is_admin());
create policy "Admins update shipments" on public.shipments for update using (public.is_admin()) with check (public.is_admin());

create policy "Admins read settings" on public.app_settings for select using (public.is_admin());
create policy "Super admin updates settings" on public.app_settings for update using (public.is_super_admin()) with check (public.is_super_admin());

create index orders_user_id_idx on public.orders(user_id);
create index orders_status_idx on public.orders(status);
create index orders_created_at_idx on public.orders(created_at desc);
create index order_items_order_id_idx on public.order_items(order_id);

commit;
