begin;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('necklace', 'ring', 'earring')),
  price integer not null check (price >= 0),
  inventory integer not null default 0 check (inventory >= 0),
  material text,
  description text,
  badge text check (badge in ('NEW', 'BEST') or badge is null),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

create policy "Public reads active products" on public.products
  for select using (active = true or public.is_admin());

create policy "Super admin manages products" on public.products
  for all using (public.is_super_admin()) with check (public.is_super_admin());

create index if not exists products_active_sort_idx on public.products (active, sort_order, created_at desc);

insert into public.products (id, name, category, price, inventory, material, description, badge, sort_order, active) values
  (1, 'Noir Rose Earrings', 'earring', 49000, 20, '925 Silver', '입체적인 장미 모티프를 절제된 실버 톤으로 완성한 이어링입니다.', 'NEW', 1, true),
  (2, 'Emerald Signet Ring', 'ring', 78000, 20, '925 Silver · Emerald', '선명한 그린 스톤과 단단한 실버 밴드가 균형을 이루는 시그넷 링입니다.', 'BEST', 2, true),
  (3, 'Coin Chain Necklace', 'necklace', 94000, 20, '925 Silver', '빈티지 코인과 서로 다른 체인의 리듬이 매력적인 레이어드 네크리스입니다.', null, 3, true),
  (4, 'Amethyst Bead Necklace', 'necklace', 69000, 20, 'Amethyst · Silver', '차분한 보랏빛 자수정 비즈에 가는 실버 체인을 더한 섬세한 네크리스입니다.', 'NEW', 4, true),
  (5, 'Bold Link Necklace', 'necklace', 109000, 20, '925 Silver', '볼드한 링크가 목선을 따라 자연스럽게 흐르는 존재감 있는 체인 네크리스입니다.', 'BEST', 5, true),
  (6, 'Lapis Coin Necklace', 'necklace', 72000, 20, 'Lapis · Silver', '깊은 청색 비즈와 작은 코인 펜던트가 매일의 룩에 잔잔한 포인트를 줍니다.', null, 6, true),
  (7, 'Classic Curb Necklace', 'necklace', 98000, 20, '925 Silver', '촘촘하게 맞물린 커브 체인의 광택이 단정하고 모던한 인상을 만듭니다.', null, 7, true),
  (8, 'Silver Sphere Necklace', 'necklace', 119000, 20, '925 Silver', '크기가 다른 실버 볼이 리드미컬하게 이어지는 조형적인 네크리스입니다.', 'BEST', 8, true),
  (9, 'Fine Layered Chain', 'necklace', 64000, 20, '925 Silver', '빛을 가볍게 머금는 두 줄의 체인으로 단정하게 레이어링한 네크리스입니다.', null, 9, true),
  (10, 'Garnet Drop Necklace', 'necklace', 76000, 20, 'Garnet · Silver', '와인빛 가넷과 작은 드롭 장식이 차분한 우아함을 전합니다.', 'NEW', 10, true),
  (11, 'Turquoise Collar', 'necklace', 88000, 20, 'Turquoise · Silver', '맑은 터키석 비즈를 촘촘히 엮어 얼굴빛을 생기 있게 밝혀주는 네크리스입니다.', null, 11, true),
  (12, 'Honey Amethyst Necklace', 'necklace', 82000, 20, 'Amethyst · Quartz', '자수정 사이에 따뜻한 꿀빛 스톤을 더한 부드럽고 독특한 조합입니다.', null, 12, true),
  (13, 'Tiger Eye Tail Necklace', 'necklace', 79000, 20, 'Tiger Eye · Silver', '깊은 갈색 타이거아이와 고래 꼬리 펜던트가 자연의 이미지를 담아냅니다.', 'NEW', 13, true)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.products', 'id'), greatest((select max(id) from public.products), 1));

commit;

